Proyecto3_GuillermoDuque_AndresArteag/Models/IdeaDeNegocio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proyecto3_GuillermoDuque_AndresArteag.Models
{
    public class IdeaDeNegocio
    {
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public string ImpactoSocialOEconomico { get; set; }
        [Display(Name = "Departamentos que se benefician")]
        public List<Departamento> DepartamentosBeneficiarios { get; set; }
        public int ValorInversion { get; set; }
        public int IngresosPrimeros3Anios { get; set; }
        public List<IntegranteEquipo> IntegrantesEquipo { get;  set; }
        public List<string> Herramienta4RIUtilizada { get; set; }

        public IdeaDeNegocio()
        {
            DepartamentosBeneficiarios = new List<Departamento>();
            IntegrantesEquipo = new List<IntegranteEquipo>();
        }
        public int Rentabilidad
        {
            get { return IngresosPrimeros3Anios - ValorInversion; }
        }
    }
}

Proyecto3_GuillermoDuque_AndresArteag/Controllers/IdeaDeNegocioController.cs
using Proyecto3_GuillermoDuque_AndresArteag.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto3_GuillermoDuque_AndresArteag.Controllers
{
    public class IdeaDeNegocioController : Controller
    {

        
        private static List<IdeaDeNegocio> ListaIdeasNegocio = new List<IdeaDeNegocio>();

        
        private static List<Departamento> ListaDepartamentos = new List<Departamento>();

        
        private static List<IntegranteEquipo> ListaIntegrantes = new List<IntegranteEquipo>();

        
        public ActionResult Index()
        {
            return View(ListaIdeasNegocio);
        }

        
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult CreateConDepartamento(IdeaDeNegocio idea, string NombreDepartamentoHidden)
        {
            if (ModelState.IsValid)
            {
                
                if (ListaIdeasNegocio.Any(i => i.Nombre == idea.Nombre))
                {
                    ModelState.AddModelError("Nombre", "Ya existe una idea de negocio con este nombre.");
                    return View(idea);
                }

                
                idea.Codigo = GenerarCodigoUnico();

                if (Request.Form.AllKeys.Any(key => key.StartsWith("IntegrantesEquipo")))
                {
                    idea.IntegrantesEquipo = new List<IntegranteEquipo>();

                    for (int i = 0; i < Request.Form.Count; i += 5)
                    {
                        idea.IntegrantesEquipo.Add(new IntegranteEquipo
                        {
                            Identificacion = Request.Form[i],
                            Nombre = Request.Form[i + 1],
                            Apellidos = Request.Form[i + 2],
                            Rol = Request.Form[i + 3],
                            Email = Request.Form[i + 4]
                        });
                    }
                }

                
                var existingDepartamento = ListaDepartamentos.FirstOrDefault(d => d.Nombre == NombreDepartamentoHidden);

                if (existingDepartamento != null)
                {
                    
                    idea.DepartamentosBeneficiarios = new List<Departamento> { existingDepartamento };
                }
                else
                {
                    
                    var nuevoDepartamento = new Departamento
                    {
                        Nombre = NombreDepartamentoHidden,
                        Codigo = GenerarCodigoUnico()
                    };

                    
                    idea.DepartamentosBeneficiarios = new List<Departamento> { nuevoDepartamento };

                    
                    ListaDepartamentos.Add(nuevoDepartamento);
                }

                
                ListaIdeasNegocio.Add(idea);


                
                ViewBag.MostrarCodigoUnico = true;
                ViewBag._CodigoUnico = idea.Codigo;

                
                Response.Cookies.Add(new HttpCookie("MostrarCodigoUnico", "true"));

                return View("_CodigoUnico"); 
            }


            return View();
        }
        public ActionResult CodigoUnico()
        {
            return View("_CodigoUnico");
        }

        [HttpPost]
        public ActionResult Create(IdeaDeNegocio idea, string Herramienta4RIUtilizadaInput)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    
                    if (ListaIdeasNegocio.Any(i => i.Nombre == idea.Nombre))
                    {
                        ModelState.AddModelError("Nombre", "Ya existe una idea de negocio con este nombre.");
                        return View(idea);
                    }

                    
                    idea.Codigo = GenerarCodigoUnico();

                    
                    var herramientas = Herramienta4RIUtilizadaInput.Split(',').Select(s => s.Trim()).ToList();

                    
                    idea.Herramienta4RIUtilizada = herramientas;

                    
                    if (idea.ValorInversion == null || idea.IngresosPrimeros3Anios == null ||
                        idea.ValorInversion == 0 || idea.IngresosPrimeros3Anios == 0)
                    {
                        throw new Exception("Los valores de inversión e ingresos no pueden ser nulos o 0.");
                    }

                    
                    if (idea.ValorInversion - idea.IngresosPrimeros3Anios < 0)
                    {
                        throw new Exception("La diferencia entre inversión e ingresos no puede ser negativa.");
                    }

                    
                    ListaIdeasNegocio.Add(idea);

                    
                    Response.Cookies.Add(new HttpCookie("MostrarCodigoUnico", "true"));

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                    return View(idea);
                }
            }
            return View(idea);
    }

        
        public ActionResult Edit(string codigo)
        {
            
            IdeaDeNegocio idea = ListaIdeasNegocio.FirstOrDefault(i => i.Codigo == codigo);

            if (idea == null)
            {
                ModelState.AddModelError("Codigo", "Código incorrecto. Inténtelo de nuevo.");
                return View();
            }

            
            return View(idea);
        }

        
        [HttpPost]
        public ActionResult Edit(IdeaDeNegocio idea)
        {
            if (ModelState.IsValid)
            {
                
                IdeaDeNegocio existingIdea = ListaIdeasNegocio.FirstOrDefault(i => i.Codigo == idea.Codigo);

                if (existingIdea == null)
                {
                    ModelState.AddModelError("Codigo", "Código incorrecto. Inténtelo de nuevo.");
                    return View(idea); 
                }

                
                
                existingIdea.ValorInversion = idea.ValorInversion;
                existingIdea.IngresosPrimeros3Anios = idea.IngresosPrimeros3Anios;

                return RedirectToAction("Index", new { codigo = existingIdea.Codigo });
            }
            return View(idea);
        }


        private string GenerarCodigoUnico()
        {
            const string caracteresPermitidos = "0123456789ABCD";
            char[] codigo = new char[6];
            Random random = new Random(); 

            for (int i = 0; i < codigo.Length; i++)
            {
                codigo[i] = caracteresPermitidos[random.Next(caracteresPermitidos.Length)];
            }
            return new string(codigo);
        }
        public ActionResult VerIdea(string codigo)
        {
            
            IdeaDeNegocio idea = ListaIdeasNegocio.FirstOrDefault(i => i.Codigo == codigo);

            if (idea == null)
            {
                
                return HttpNotFound();
            }

            
            var departamentos = idea.DepartamentosBeneficiarios;
            var integrantes = idea.IntegrantesEquipo;

            
            ViewBag.Departamentos = departamentos;
            ViewBag.Integrantes = integrantes;

            return View(idea);
        }



        public ActionResult Estadisticas()
        {
            var ideas = ListaIdeasNegocio;

      
            var ideasOrdenadas = ideas.OrderByDescending(i => i.Rentabilidad);
            var ideasMasRentables = ideasOrdenadas.Take(3);

            var sumaTotalIngresos = ideas.Sum(i => i.IngresosPrimeros3Anios);

           
            var sumaTotalInversion = ideas.Sum(i => i.ValorInversion);


            var ideasConIA = ideas.Where(i => i.Herramienta4RIUtilizada.Any(h => h.ToLower().Contains("inteligencia artificial"))).ToList();


            var ideasDesarrolloSostenible = ideas.Where(i => i.ImpactoSocialOEconomico.ToLower().Contains("desarrollo sostenible")).ToList();

            IdeaDeNegocio ideaMayorImpacto = ListaIdeasNegocio.OrderByDescending(idea => idea.DepartamentosBeneficiarios.Count).FirstOrDefault();
            IdeaDeNegocio ideaMayorIngresos = ListaIdeasNegocio.OrderByDescending(idea => idea.IngresosPrimeros3Anios).FirstOrDefault();

            ViewBag.IdeasMasRentables = ideasMasRentables;
            ViewBag.IdeaMayorImpacto = ideaMayorImpacto;
            ViewBag.SumaTotalIngresos = sumaTotalIngresos;
            ViewBag.SumaTotalInversion = sumaTotalInversion;
            ViewBag.IdeasConIA = ideasConIA;
            ViewBag.IdeasDesarrolloSostenible = ideasDesarrolloSostenible;

            if (ideaMayorIngresos != null)
            {
                ViewBag.IdeaMayorIngresos = ideaMayorIngresos;
            }
            
            return View();

        }

    }
}

Proyecto3_GuillermoDuque_AndresArteag/Views/IdeaDeNegocio/Create.cshtml
@model Proyecto3_GuillermoDuque_AndresArteag.Models.IdeaDeNegocio

<h2>Crear Idea de Negocio</h2>

@using (Html.BeginForm("CreateConDepartamento", "IdeaDeNegocio", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, "Nombre")
        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Nombre)
    </div>

    <div id="integrantesContainer">
        
    </div>

    <button type="button" id="agregarIntegranteBtn" class="btn btn-primary">Agregar Integrante</button>

    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <script>
        $(document).ready(function () {
    var contadorIntegrantes = 0;

    $('#agregarIntegranteBtn').click(function () {
        contadorIntegrantes++;

        
        var integranteHtml = '<div class="integrante">';
        integranteHtml += '<input type="text" class="form-control" name="Integrantes[' + contadorIntegrantes + '].Identificacion" placeholder="Identificación">';
        integranteHtml += '<input type="text" class="form-control" name="Integrantes[' + contadorIntegrantes + '].Nombre" placeholder="Nombre">';
        integranteHtml += '<input type="text" class="form-control" name="Integrantes[' + contadorIntegrantes + '].Apellidos" placeholder="Apellidos">';
        integranteHtml += '<input type="text" class="form-control" name="Integrantes[' + contadorIntegrantes + '].Rol" placeholder="Rol">';
        integranteHtml += '<input type="text" class="form-control" name="Integrantes[' + contadorIntegrantes + '].Email" placeholder="Email">';
        integranteHtml += '</div>';

        
        $('#integrantesContainer').append(integranteHtml);

        
        var integrante = {
            Identificacion: "",
            Nombre: "",
            Apellidos: "",
            Rol: "",
            Email: ""
        };

        
        idea.IntegrantesEquipo.push(integrante);
    });
});

    </script>


    <div class="form-group">
        @Html.LabelFor(model => model.ImpactoSocialOEconomico, "Impacto Social o Económico")
        @Html.TextBoxFor(model => model.ImpactoSocialOEconomico, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ImpactoSocialOEconomico)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ValorInversion, "Valor de Inversión")
        @Html.TextBoxFor(model => model.ValorInversion, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ValorInversion)
    </div>

    <div class="form-group">
        @Html.Label("Nombre del Departamento que se beneficia")
        <input type="text" class="form-control" name="NombreDepartamento" />
    </div>
    <input type="hidden" name="NombreDepartamentoHidden" id="NombreDepartamentoHidden" />

    <script>
        $(document).ready(function () {
            $('#NombreDepartamento').blur(function () {
                var nombreDepartamento = $(this).val();
                $('#NombreDepartamentoHidden').val(nombreDepartamento);
            });
        });
    </script>

    <div class="form-group">
        @Html.LabelFor(model => model.IngresosPrimeros3Anios, "Ingresos Primeros 3 Años")
        @Html.TextBoxFor(model => model.IngresosPrimeros3Anios, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IngresosPrimeros3Anios)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Herramienta4RIUtilizada, "Herramienta 4RI Utilizada")
        @Html.TextBoxFor(model => model.Herramienta4RIUtilizada, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Herramienta4RIUtilizada)
    </div>

    <script>
    $(document).ready(function () {
        
        $('#impactoInput').on('input', function () {
            var inputValue = $(this).val().toLowerCase();
            $(this).val(inputValue);
        });

        
        $('#herramientaInput').on('input', function () {
            var inputValue = $(this).val().toLowerCase();
            $(this).val(inputValue);
        });
    });
</script>

    

    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>
}
<script>
    @if (ViewBag.MostrarCodigoUnico != null && ViewBag.CodigoUnico != null)
    {
        <text>
        $(document).ready(function() {
            alert("Se ha generado un código único para la idea de negocio:\n\n@ViewBag.CodigoUnico");
        });
        </text>
    }


Proyecto3_GuillermoDuque_AndresArteag/Views/IdeaDeNegocio/Edit.cshtml
@model Proyecto3_GuillermoDuque_AndresArteag.Models.IdeaDeNegocio

<h2>Editar Idea de Negocio</h2>

@using (Html.BeginForm("Edit", "IdeaDeNegocio", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Codigo)
        @Html.TextBoxFor(model => model.Codigo)
        @Html.ValidationMessageFor(model => model.Codigo)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ValorInversion)
        @Html.TextBoxFor(model => model.ValorInversion, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ValorInversion)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IngresosPrimeros3Anios)
        @Html.TextBoxFor(model => model.IngresosPrimeros3Anios, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IngresosPrimeros3Anios)
    </div>

    <button type="submit" class="btn btn-primary">Guardar Cambios</button>

}









Proyecto3_GuillermoDuque_AndresArteag/Views/IdeaDeNegocio/Estadisticas.cshtml
@model Proyecto3_GuillermoDuque_AndresArteag.Models.IdeaDeNegocio

@{
    ViewBag.Title = "Estadísticas";
}

<h2>Estadísticas</h2>

@if (ViewBag.IdeaMayorImpacto != null)
{
    <h4>Idea de negocio con mayor impacto en departamentos:</h4>
    <p>@ViewBag.IdeaMayorImpacto.Nombre</p>
    @Html.ActionLink("Ver", "VerIdea", new { codigo = ViewBag.IdeaMayorImpacto.Codigo }, new { @class = "btn btn-primary" })
}

@if (ViewBag.IdeaMayorIngresos != null)
{
    <h4>Idea de negocio con mayor total de ingresos en los primeros 3 años:</h4>
    <p>@ViewBag.IdeaMayorIngresos.Nombre</p>
    @Html.ActionLink("Ver", "VerIdea", new { codigo = ViewBag.IdeaMayorIngresos.Codigo }, new { @class = "btn btn-primary" })
}
<h4>Las 3 Ideas de Negocio Más Rentables:</h4>
<ul>
    @foreach (var idea in ViewBag.IdeasMasRentables)
    {
        <li>@idea.Nombre - Rentabilidad: @idea.Rentabilidad</li>
    }
</ul>

<h4>Suma Total de Ingresos de Todas las Ideas de Negocio: @ViewBag.SumaTotalIngresos</h4>
<h4>Suma Total de Inversión en Todas las Ideas de Negocio: @ViewBag.SumaTotalInversion</h4>

<h4>Ideas de Negocio con Inteligencia Artificial:</h4>
<ul>
    @foreach (var idea in ViewBag.IdeasConIA)
    {
        <li>@idea.Nombre</li>
        @Html.ActionLink("Ver", "VerIdea", new { codigo = ViewBag.IdeaMayorImpacto.Codigo }, new { @class = "btn btn-primary" })
    }
</ul>

<h4>Ideas de Negocio con "Desarrollo sostenible" en Impacto Social o Económico:</h4>
<ul>
    @foreach (var idea in ViewBag.IdeasDesarrolloSostenible)
    {
        <li>@idea.Nombre</li>
        @Html.ActionLink("Ver", "VerIdea", new { codigo = ViewBag.IdeaMayorImpacto.Codigo }, new { @class = "btn btn-primary" })
    }
</ul>

<div>
    @Html.ActionLink("Volver a la Lista", "Index")
</div>

Proyecto3_GuillermoDuque_AndresArteag/Views/IdeaDeNegocio/Index.cshtml
@model IEnumerable<Proyecto3_GuillermoDuque_AndresArteag.Models.IdeaDeNegocio>

<h2>Lista de Ideas de Negocio</h2>

<p>
    @Html.ActionLink("Crear Nueva", "Create")
</p>

<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
           

            <td>
                <a href="@Url.Action("Edit", "IdeaDeNegocio", new { codigo = item.Codigo })">Editar</a>
            </td>
        </tr>
    }
</table>

Proyecto3_GuillermoDuque_AndresArteag/Views/IdeaDeNegocio/VerIdea.cshtml

@model Proyecto3_GuillermoDuque_AndresArteag.Models.IdeaDeNegocio

@{
    ViewBag.Title = "Detalles de Idea de Negocio";
}

<h2>Detalles de Idea de Negocio</h2>

<table class="table">
    <tr>
        <th>Código</th>
        <td>@Model.Codigo</td>
    </tr>
    <tr>
        <th>Nombre</th>
        <td>@Model.Nombre</td>
    </tr>
    <tr>
        <th>Impacto Social o Económico</th>
        <td>@Model.ImpactoSocialOEconomico</td>
    </tr>
    <tr>
        <th>Valor de Inversión</th>
        <td>@Model.ValorInversion</td>
    </tr>
    <tr>
        <th>Ingresos Primeros 3 Años</th>
        <td>@Model.IngresosPrimeros3Anios</td>
    </tr>
    <tr>
        <th>Herramienta 4RI Utilizada</th>
        <td>@Model.Herramienta4RIUtilizada</td>
    </tr>
</table>

@Html.ActionLink("Volver a la Lista", "Index")


Proyecto3_GuillermoDuque_AndresArteag/Views/IdeaDeNegocio/_CodigoUnico.cshtml
<div id="codigoUnicoModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Código Único de la Idea de Negocio</h4>
            </div>
            <div class="modal-body">
                <p>El código único de la idea de negocio es: <strong>@ViewBag._CodigoUnico</strong></p>
            </div>
            <div class="modal-footer">
                <a href="/IdeaDeNegocio/Index" class="btn btn-primary">Inicio</a>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<script>
    $(document).ready(function () {
        $('#codigoUnicoModal').modal('show');
    });
</script>




